#
#    Dashboard Automation Reports App
#

version: '3'

services:

  #############################################################################
  # Automation Reports Service
  #############################################################################
  dashboard-automation-app:
    image: "dashboard-automation-app:latest"
    container_name: dashboard-automation-app
    restart: always
    environment:
      - DASHBOARD_AUTOMATION_APP_PORT=${DASHBOARD_AUTOMATION_APP_PORT}
      - DASHBOARD_APP_URL=${DASHBOARD_APP_URL}
      - PILOTCTL_URI=${PILOTCTL_URI}
      - PILOTCTL_APP_PILOTCTL_ONIX_USER=${PILOTCTL_APP_PILOTCTL_ONIX_USER}
      - PILOTCTL_APP_PILOTCTL_ONIX_PWD=${PILOTCTL_APP_PILOTCTL_ONIX_PWD}
    ports:
      - "4000:4000"